## YAML Template.
---
server:
    servlet:
        context-path: 
    port: 4000
logging:
    level:
        org:
            hibernate:
                SQL: INFO
                descriptor:
                    sql:
                        BasicBinder: TRACE
            springframework: INFO
            thymeleaf: TRACE
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/por_maria_bd
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: admin
        validation-query: SELECT 1
    hikari:
        min-idle: 1
        max-pool-size: 10
    jpa:
        show-sql: true
#        defer-datasource-initialization: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
            naming:
                strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                globally_quoted_identifiers: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
    thymeleaf:
        cache: false
        check-template: true
        check-template-location: true
        content-type: text/html
        enabled: true
        encoding: UTF-8
    h2:
        console:
            path: /h2-ui